using AiBusinessPlatform.Api.Assistant;
using AiBusinessPlatform.Api.Endpoints;
using AiBusinessPlatform.Api.Orchestrator;
using AiBusinessPlatform.Api.Payments;
using AiBusinessPlatform.Application.Abstractions;
using AiBusinessPlatform.Application.Auth;
using AiBusinessPlatform.Application.Tools;
using AiBusinessPlatform.Domain.Entities;
using AiBusinessPlatform.Infrastructure.AI;
using AiBusinessPlatform.Infrastructure.Auth;
using AiBusinessPlatform.Infrastructure.Data;
using AiBusinessPlatform.Infrastructure.Messaging;
using AiBusinessPlatform.Infrastructure.Payments;
using AiBusinessPlatform.Infrastructure.Tools;
using AiBusinessPlatform.Infrastructure.WhatsApp;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.AI;
using Microsoft.OpenApi.Models;
using OpenAI;
using QuestPDF.Infrastructure;
using System.ClientModel;

// QuestPDF Community license — free for businesses under $1M/yr revenue, otherwise a paid license
// (https://www.questpdf.com/license/) — required once at startup before any document is generated.
QuestPDF.Settings.License = LicenseType.Community;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddHttpContextAccessor();

// Enums (order/approval/catalog-item/WhatsApp-connection status, etc.) serialize as readable
// names instead of raw ints — the only consumer of this Api's JSON today is the mobile dashboard.
builder.Services.ConfigureHttpJsonOptions(options =>
    options.SerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter()));

// Section 12.3/18 — Swagger UI for manually exercising every endpoint (dashboard + auth). The
// document itself is generated by the built-in Microsoft.AspNetCore.OpenApi (AddOpenApi/MapOpenApi
// below); a Bearer security scheme is registered here so Swagger UI's "Authorize" button attaches
// the token to every request without needing a browser extension or manual header entry.
builder.Services.AddOpenApi(options =>
{
    options.AddDocumentTransformer((document, _, _) =>
    {
        document.Components ??= new OpenApiComponents();
        document.Components.SecuritySchemes["Bearer"] = new OpenApiSecurityScheme
        {
            Type = SecuritySchemeType.Http,
            Scheme = "bearer",
            BearerFormat = "JWT",
            In = ParameterLocation.Header,
            Description = "Paste the token returned by POST /api/auth/login or /api/auth/signup."
        };
        document.SecurityRequirements.Add(new OpenApiSecurityRequirement
        {
            [new OpenApiSecurityScheme { Reference = new OpenApiReference { Id = "Bearer", Type = ReferenceType.SecurityScheme } }] = []
        });
        return Task.CompletedTask;
    });
});

builder.Services.AddDbContext<AiBusinessPlatformDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("Default"), o => o.UseVector()));

builder.Services.Configure<RabbitMqOptions>(builder.Configuration.GetSection(RabbitMqOptions.SectionName));
builder.Services.AddSingleton<IQueuePublisher, RabbitMqQueuePublisher>();

// Bridges a mid-tool-call MCP elicitation request (raised inside an in-flight /api/assistant/chat
// request) to the separate POST /api/assistant/elicit/{id} request the human's answer arrives on —
// see ElicitationRegistry's own remarks. Process-wide singleton by design (see file for why).
builder.Services.AddSingleton<ElicitationRegistry>();

// Resolves business_id/user_id from the authenticated JWT (Section 14). Registered as ONE scoped
// instance forwarded to all three interfaces — a naive AddScoped<T> per interface would create
// separate instances and break WhatsAppOrchestratorConsumer's SetBusinessId call (Section 9.3),
// which pushes a business_id resolved outside any HttpContext into this same scoped instance.
builder.Services.AddScoped<HttpBusinessIdTenantProvider>();
builder.Services.AddScoped<ICurrentTenantProvider>(sp => sp.GetRequiredService<HttpBusinessIdTenantProvider>());
builder.Services.AddScoped<ICurrentTenantSetter>(sp => sp.GetRequiredService<HttpBusinessIdTenantProvider>());
builder.Services.AddScoped<ICurrentUserProvider>(sp => sp.GetRequiredService<HttpBusinessIdTenantProvider>());
builder.Services.AddScoped<ICurrentUserRoleProvider>(sp => sp.GetRequiredService<HttpBusinessIdTenantProvider>());
builder.Services.AddScoped<ICurrentCustomerProvider, HttpCustomerAccountProvider>();
builder.Services.AddScoped<IPermissionChecker, PermissionChecker>();

// Section 15 — JWT auth. PasswordHasher<BusinessUser> + a hand-issued JWT satisfy "ASP.NET Core
// Identity or an equivalent" without adopting full Identity's UserManager/table scaffolding.
builder.Services.AddSingleton<IPasswordHasher<BusinessUser>, PasswordHasher<BusinessUser>>();
builder.Services.AddSingleton<IPasswordHasher<CustomerAccount>, PasswordHasher<CustomerAccount>>();
builder.Services.AddPlatformJwtAuthentication(builder.Configuration);

// Section 10.3/10.7 tool contracts — same registrations the Mcp project's host uses, so both
// entry points resolve to identical implementations.
builder.Services.AddScoped<IHealthTool, HealthTool>();
builder.Services.AddScoped<ICatalogTools, CatalogTools>();
builder.Services.AddScoped<IOrderTools, OrderTools>();
builder.Services.AddScoped<IPaymentTools, PaymentTools>();
builder.Services.AddScoped<IDeliveryTools, DeliveryTools>();
builder.Services.AddScoped<IApprovalTools, ApprovalTools>();
builder.Services.AddScoped<IRagTools, RagTools>();
builder.Services.AddScoped<IInsightsTools, InsightsTools>();
builder.Services.AddScoped<ICustomerTools, CustomerTools>();
builder.Services.AddScoped<ISupplierTools, SupplierTools>();
builder.Services.AddScoped<IPurchaseOrderTools, PurchaseOrderTools>();
builder.Services.AddScoped<IMarketplaceTools, MarketplaceTools>();
builder.Services.AddScoped<IDocumentGenerationTools, DocumentGenerationTools>();
builder.Services.AddScoped<IMessagingTools, MessagingTools>();
builder.Services.AddScoped<IStaffTools, StaffTools>();

// Section 10.2 — where the Assistant chat endpoint finds the platform's own MCP server (it
// connects as a real MCP client, forwarding the caller's own bearer token).
builder.Services.Configure<McpServerOptions>(builder.Configuration.GetSection(McpServerOptions.SectionName));

builder.Services.AddHealthChecks()
    .AddNpgSql(builder.Configuration.GetConnectionString("Default") ?? string.Empty, name: "postgres");

// Section 10.2 — the same LM Studio + tool-calling recipe already proven in the
// OrchestratorHarness console app, now wired into a real hosted service.
builder.Services.Configure<LmStudioOptions>(builder.Configuration.GetSection(LmStudioOptions.SectionName));
builder.Services.AddSingleton<IChatClient>(sp =>
{
    var options = sp.GetRequiredService<Microsoft.Extensions.Options.IOptions<LmStudioOptions>>().Value;
    if (string.IsNullOrWhiteSpace(options.Model))
    {
        throw new InvalidOperationException("LmStudio:Model is not configured (appsettings.json).");
    }

    var openAIClient = new OpenAIClient(
        new ApiKeyCredential(options.ApiKey),
        new OpenAIClientOptions { Endpoint = new Uri(options.BaseUrl) });

    IChatClient innerChatClient = openAIClient.GetChatClient(options.Model).AsIChatClient();
    return new ChatClientBuilder(innerChatClient).UseFunctionInvocation().Build();
});

// Section 10.6 — RAG embeddings, same LM Studio server as the chat client, different model.
builder.Services.AddSingleton<IEmbeddingGenerator<string, Embedding<float>>>(sp =>
    LmStudioEmbeddingGeneratorFactory.Create(sp.GetRequiredService<Microsoft.Extensions.Options.IOptions<LmStudioOptions>>().Value));

// Section 13.1 — real outbound WhatsApp sends via Meta's Graph API. Base address only carries
// the host; WhatsAppGraphClient supplies the versioned path per call. A resilience handler covers
// transient network failures — the app-level try/catch around the send call (see
// WhatsAppOrchestratorConsumer) still handles genuine failures (bad token, no connection, etc.)
// without crashing or nacking the queue message.
builder.Services.Configure<WhatsAppOptions>(builder.Configuration.GetSection(WhatsAppOptions.SectionName));
builder.Services.AddHttpClient<IWhatsAppSender, WhatsAppGraphClient>(client =>
{
    client.BaseAddress = new Uri("https://graph.facebook.com/");
}).AddStandardResilienceHandler();
builder.Services.AddScoped<IWhatsAppMessageService, WhatsAppMessageService>();

// Section 13.2 — real outbound Paynow Express Checkout calls. No BaseAddress here since
// PaynowClient builds full URLs itself from PaynowOptions.BaseUrl (matches the WhatsApp client's
// resilience-handler pattern).
builder.Services.Configure<PaynowOptions>(builder.Configuration.GetSection(PaynowOptions.SectionName));
builder.Services.AddHttpClient<IPaynowClient, PaynowClient>().AddStandardResilienceHandler();

builder.Services.AddHostedService<WhatsAppOrchestratorConsumer>();
builder.Services.AddHostedService<PaymentWebhookConsumer>();
builder.Services.AddHostedService<WhatsAppRetryHostedService>();

// Dev-only permissive CORS so the Expo web preview (a different origin/port) can call this Api.
// Native (iOS/Android) builds aren't subject to CORS, so this only matters for the web target.
const string devCorsPolicy = "DevCors";
builder.Services.AddCors(options =>
{
    options.AddPolicy(devCorsPolicy, policy => policy
        .SetIsOriginAllowed(_ => true)
        .AllowAnyHeader()
        .AllowAnyMethod());
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    app.UseSwaggerUI(options => options.SwaggerEndpoint("/openapi/v1.json", "AI Business Platform API"));
    app.UseCors(devCorsPolicy);
}

app.UseAuthentication();
app.UseAuthorization();

app.MapHealthChecks("/health");

app.MapAuthEndpoints();
app.MapCustomerAuthEndpoints();
app.MapWebhookEndpoints();
app.MapDashboardEndpoints();
app.MapStaffEndpoints();
app.MapMarketplaceEndpoints();
app.MapAssistantEndpoints();

app.Run();
